# Permalinks
permalink:           /blog/:title

# Setup
title:              Erik Fredner 
url:                http://erikfredner.com 
baseurl:             ""
paginate: 1
paginate_path: "blog/page/:num/"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:             Erik Fredner 
  url:               https://twitter.com/erikfredner
  email:             fredner@stanford.edu

# Custom vars
pages_list:
        About: '/about'
        Contact: '/contact'
        CV: '/cv'
        Blog: '/blog'

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
